### ISSUE TITLE
find_zero documentation and option documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaMath/Roots.jl#101]
It seems that `find_zero` is the newer interface with all the good algorithms and I am enjoying it, but it's lacking docs. Because of all of the kwarg splatting it can be a bit hard to find out what the total option set is for example. And how are the tolerances defined, i.e. what do they mean? Is convergence when both absolute and relative tolerance are met? What is the relative tolerance of a zero? Stuff like that.

**Comment by juliohm** [comment]
I came across this issue today, feeling the same about the docs.

**Comment by rafaqz** [comment]
Same again. I would give the alternative find_zero methods precedence in the docs and the readme over the matlab style fzero, the new style is better!

**Comment by ChrisRackauckas** [comment]
Looks like it.
