### ISSUE TITLE
Unitful support

### ISSUE THREAD

**Issue by rafaqz** [JuliaMath/Roots.jl#103]
I hoped something like this would work:

```
using Unitful
using Roots
find_zero(x -> x + 5u"g", (-100u"g",100u"g"), FalsePosition())
```
But Roots.jl is too strongly typed. I was also hoping a fix would be trivial but it seems like UnivariateZeroProblem and UnivariateZeroOptions would have to be refactored so that the input type propagates through to all the tolerances, and probably other things.

**Comment by jverzani** [comment]
Hmm, this seems quite reasonable. Let me investigate.

**Comment by rafaqz** [comment]
There is also the problem of Complex in the union type on UnivariateZeroProblem. Complex takes Real numbers but Units are of type Number.

**Comment by jverzani** [comment]
There are quite a few issues. I'm not familiar with Unitful, but except for the most basic bisection method, the algorithms use values of f(x_i) to produce x_{i+1}. This means that slope-like computations using f(x) must keep the units as well as function calls, so simple examples like `find_zero(x -> x^2 - 2, 1u"m")` will necessarily fail. Can you indicate what type of calls you want to do and the expected output, so I can make sure I'm no the same page when I look into this.

**Comment by rafaqz** [comment]
I'm not sure _exactly_ what you mean by the type of call I want but I'm writing libraries for physiological modelling, with sub-functions that need root finding, all bracketed. They return things like a temperature in Kelvin, or a rate such as "mol*mol^-1*s^-1", so I would be using find_zero with a bracket. But I guess I will need other methods in future as well.

I could strip the units out and add them afterwards, but its asking for bugs every time you do that (actually the reason I made this issue, stripping units before find_zero caused a bug). Also most of the functions should be independently useful library calls. As much as possible they should also be able to run without knowing about units at all - units are only passed in on parameters. Actively adding and stripping units violates that condition somewhat.

At the moment I have a little roots module for this with a few routines like secant and zbrent rewritten to handle Unitful units. It doesn't "know" about or depend on Unitful but it lets units pass through with loose typing, ie Number not Real, and care with any >= 0 etc condition to multiply the zero so it has units. 

I don't want to depend on my own very bare-bones roots module in a library when Roots.jl  exists, but also not sure exactly where to help out with Roots.jl either as I don't understand the whole picture of how it all has to work.

**Comment by ikirill** [comment]
@rafaqz I'm not very familiar with Unitful, but you said you'd rewritten a few routines. I think that's not necessary, it might be easier to add an overload that just automatically strips and reintroduces units like this:
```
find_zero(f, bracket::NTuple{2,<:Unitful.Quantity}) = unit(bracket[1]) * findzero(x -> f/unit(f(0)), (bracket[1]/unit(bracket[1]), bracket[2]/unit(bracket[1]))
```
like a wrapper around find_zero

**Comment by jverzani** [comment]
That's an easy fix. Great idea.

It would be nice to get the original  proposal to work. At one point, the flow of this package got more complicated in anticipation of some cross package standardization. I don't think that will ever happen. Perhaps with changes for `v0.7` some of the redirection can be taken out and the types loosened up in the process.

**Comment by rafaqz** [comment]
I know a wrapper like that is an option, but I'm not sure it's a good option. I was hoping that as much as many as possible of my libraries don't depend on Unitful --  but can accept Uniftul types. And that wrapper is an explicit unitful dependency. Also using units should ultimately just work in Roots.jl, otherwise everyone using Roots.jl will have to write that wrapper, and be disappointed when the simple case fails in the REPL.

There also does seem to be a bit of complexity built up in this module, that's the reason this is an issue not a pull request. I'm not sure which routines would be broken making the required changes and how they all interact. But I agree loosening the types is the best outcome in v0.7.

 It seems like DifferentialEquations.jl deals with this problem well, it doesn't depend on unitful as far as I can tell.

**Comment by ikirill** [comment]
So is the issue here just that `Unitful.Quantity <: Number`, not `Real`?

**Comment by rafaqz** [comment]
Yes, one of the issues. Having Complex in the union type on UnivariateZeroProblem also forces that because `Complex{T<:Real} <: Number` and T is shared for the union. 

Also `secant()` in bracketing has the line `tol = eps(T)*5` that only accepts `T <: AbstractFloat`, adjust_bracket(x0)` has  `u, v = float.(x0)` and `a42() has `xtol=zero(float(a))`,
. That means that T is *not* Real for any bracketing find_zero, but effectively AbstractFloat. Int is actually converted to Float for all bracketing problems:

```
julia> typeof(find_zero(x -> x + 1, (-4, 4)))                             
Float64   
```
Which is also less than ideal.

This is another problem:
```
mutable struct UnivariateZeroOptions{T}
    xabstol::T
    xreltol::T
    abstol::T
    reltol::T
...
```

For every problem all of these are set, although most don't use more than half of them. Relative tolerances are multipliers, so type doesn't matter, while abs tolerances need the right type, and need to be passed in - but doesn't have to be the same T as reltol. Those type params could be split into {A,R}, but then as far as I can tell all bracketing problems only actually need one `tol` arg, so the other one is not used-- but still passed around and required in kwargs if using non-float types. I don't understand why the whole UnivariateZeroOptions{T} struct is even needed??


Looking through it all I can see the attractiveness of the simple wrapper solution. But I think a cleaner architecture would be better for a lot more reasons than just Unitful, the problem really seems to be that this package is limited to handling AbstractFloat.

**Comment by ikirill** [comment]
Most of those rootfinding methods are indeed limited to floats, almost by design. There would be some risk of unintended consequences if you took that away I think.

Re your examples: I think `eps(5.0u"g") === 8.881784197001252e-16 g` works as expected, and so does `float(5u"g") === 5.0 g`, I'm not sure that's an issue here. Conversion Int -> Float64 also seems correct, and matches the behaviour of every other rootfinding library I've ever seen.

**Comment by rafaqz** [comment]
Sure, but I was mostly trying to point out all the ways Units would not flow through Roots.jl, and yes I messed some of it up - it took me a few late night hours as it was to follow everything around. The second paragraph of problems all do seem to work with units if they are floats (while eps(1//2u"g") does not), and my integer point is irrelevant! Forgive me, I'm an ecologist, not a mathematician.

But the Complex{T<:Real} problem and the xtol T problems do block the use of units as far as I can tell, and would need to be refactored somehow.

**Comment by rafaqz** [comment]
As an example of how I imagined this would work this secant and bisection function handle units in Float or Rational:

```
function find_zero(f, bracket, ::Secant; xtol=1e-7, max_iter=100)
    local x
    x0, x1 = bracket
    y0, y1 = f(x0), f(x1) 

    for _ in 1:max_iter
        x = x1 - y1 * (x1 - x0) / (y1 - y0)
        if abs(x - x1) < xtol return x end
        x0 = x1
        y0 = y1
        x1 = x
        y1 = f(x1)
    end
    error("Root not found")
end
                                                                                        

function find_zero(f, bracket, ::Bisection; xtol=1e-7, max_iter=100)
    a, b = bracket
    fa = f(a)
    local c
    for _ in 1:max_iter
        if (b - a) <= xtol return b end

        c = (a + b)/2 
        fc = f(c)
        if fa * fc > 0.0(fa * fc)
            a = c 
            fa = fc
        elseif fc == 0.0fc
            return c
        else
            b = c 
        end
    end

    error("Root not found")
end

julia> using Unitful
julia> find_zero(x -> x + 1//2u"g", (-4//1u"g", 4//1u"g"), Bisection(); xtol=1//100000u"g")
-1//2 g^-1

julia> find_zero(x -> x + 1.0u"g", (-4.0u"g", 4.0u"g"), Bisection(); xtol=1e-7u"g")
-1.0 g

julia> x = find_zero(x -> x - 20//2u"g", (-20//1u"g", 20//1u"g"), Secant(); xtol=1//10000u"g")   
10//1 g^-1                                                                                       

julia> x = find_zero(x -> x - 10.0u"g", (-20.01u"g", 20.0u"g"), Secant(); xtol=1e-7u"g")         
10.0 g                                                                                           


```

**Comment by rafaqz** [comment]
Further on the point of floats and a42 and Float, accuracy, cant we have that cake and eat it too just by using multiple dispatch for any line that needs to handle specific types?

**Comment by ikirill** [comment]
I notice that after defining a simplistic wrapper like this, a42 already works correctly, so it does seem a little surprising why Unitful.Quantity would be problematic.

```
julia> struct A <: Real; a :: Float64; end
julia> Base.convert(::Type{AbstractFloat}, a::A) = a.a
julia> Roots.find_zero(a -> a*a-2, (A(0.5), A(2.0)), Roots.A42())
1.414213562373095
```

The same code with Unitful.Quantity instead of A, which are both similar wrappers, fails looking up a method of Roots.UnivariateZeroProblem. I suspect that something goes wrong in the method dispatch and that most methods' code can work unchanged.

It can't be because Roots requires AbstractFloats in a few places, because Unitful seems to already handle that: `AbstractFloat(1.0u"g") === 1.0`.

Also, I wasn't trying to pick on you up above, sorry if it came across that way, my bad. I was trying to pick on examples (not you!) because I thought they didn't support your point.

**Comment by ikirill** [comment]
(I posted then deleted one message just now because I'd messed up my git and it wasn't valid, sorry about that.)

**Comment by ikirill** [comment]
rafaqz: I didn't mean to pick on you there, sorry if it came across like that, my bad. I was picking on your examples (not you!) that I thought didn't support your own point.

**Comment by jverzani** [comment]
In case it isn't clear, that sketch needs some work still, for sure in the functions `setup_options_state` and `univariate_zero_options`, and maybe elsewhere but shows that the current framework could likely be modified with modest adjustments.

**Comment by rafaqz** [comment]
I was thinking about that reltol eps(x) problem too, I imagine reltol should still be calibrated to the float implementation used in the unit - but it can't actually have units. I'm not sure how to do that without actually depending on Unitful.

What are the consequences for float behaviour of changing the default from eps(x) to eps() ? Because that would solve it. Does it mean slower execution time for larger float values that would have had a higher eps() and reltol values? (I don't think I totally understand the reasons for eps()).

The worst case is that use with Unitful always needs both reltol and abstol in kwargs, which isn't really that bad. But it _would_ be more satisfying if it worked without that.

**Comment by rafaqz** [comment]
Actually I think it's easily fixed leaving the behaviour as-is, you can strip the units with division by typeof(x)(1):

```
julia> x = 5.0u"g"                                      
5.0 g                                                                                              

julia> eps(x)/typeof(x)(1)                              
8.881784197001252e-16                                   

julia> y = 5.0                                          
5.0                                                     

julia> eps(y)/typeof(y)(1)                              
8.881784197001252e-16  

julia> isapprox(x, 5.0u"g", rtol=eps(x)/typeof(x)(1))                                            
true                                                                                                                       
```

**Comment by jverzani** [comment]
That's clever. I added it (using `oneunit`) to a revised version of the gist. 

I need to check that it works with some other methods, but it looks promising, and hopefully a bit tidier.

**Comment by rafaqz** [comment]
Great, that's looking pretty close now.

**Comment by jverzani** [comment]
I did a bit more cleanup. Will sit on this for a day or so to see if there are other things to touch, then start integrating it into the code base. It shouldn't be too hard. Thanks for the push to look at this.

**Comment by rafaqz** [comment]
No worries, thanks for making it happen. I was thinking while you were moving code around, it could be good to have all the types and structs in a separate types.jl file? I was getting lost in the codebase at times, and having types all together seems to help getting an overview more quickly.

**Comment by ikirill** [comment]
@jverzani OT, but I was reading this conversation so can I point out something curious about your patch: 

> "relaxed expectation that numbers were Real to them being a subtype of Number."
> "Automatic derivatives don't propogate through `Unitful`"

ForwardDiff seems to not work with Unitful for what I think is the same reason Roots used to not work with it:

```
julia> derivative(x -> x*x, 1.0u"g")
ERROR: MethodError: no method matching derivative(::##3#4, ::Unitful.Quantity{Float64,Unitful.Dimensions{(Unitful.Dimension{:Mass}(1//1),)},Unitful.FreeUnits{(Unitful.Unit{:Gram,Unitful.Dimensions{(Unitful.Dimension{:Mass}(1//1),)}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Mass}(1//1),)}}})
Closest candidates are:
  derivative(::F, ::R<:Real) where {F, R<:Real} at /Users/kirill/.julia/v0.6/ForwardDiff/src/derivative.jl:13
  derivative(::Any, ::AbstractArray, ::Real) at /Users/kirill/.julia/v0.6/ForwardDiff/src/derivative.jl:27
  derivative(::Any, ::AbstractArray, ::Real, ::ForwardDiff.DerivativeConfig{T,D} where D) where T at /Users/kirill/.julia/v0.6/ForwardDiff/src/derivative.jl:27
  ...
```

There must be other places with the same issue too, it's probably not specific to Roots.

**Comment by jverzani** [comment]
Interesting @ikirill . Integrating in units wasn't too hard outside of finding the appropriate places to divide by `oneunit` when something unitless is desired. Maybe @rafaqz can open an issue there.

**Comment by ikirill** [comment]
It could also be said that Unitful.Quantity should be `<:Real` in the first place, it's not clear to me which of those packages is in error.
