### ISSUE TITLE
Find_zeros is missing roots that are basically on top of each other 

### ISSUE THREAD

**Issue by djsegal** [JuliaMath/Roots.jl#107]
So as mentioned on discourse, I've been running sweeps to get roots at multiple inputs:

![roots](https://user-images.githubusercontent.com/3156114/41513803-7792c9ec-726f-11e8-84a6-df38cde18659.png)

In that plot, `T_bar` is some parameter I'm sweeping and `I_P` is what was found through `find_zeros`

------

As you can see, there are some markers missing at some points where the solutions are relatively close to each other. (I added green `?`'s to highlight them)

I think this is because the `rtol` for `Float64` are ignored. I tried using `BigFloat`s, but the roots are still missing.

Is there anyway to resolve this, or is it a limit of accuracy?

**Comment by jverzani** [comment]
The implementation is quite naive (and should be improved). It starts by dividing the interval into 101 subintervals and looks at each one. You can either make the interval more narrow or increase the number of pts used through `no_pts`. The tolerances are ignored for bracketing intervals. They are used for non-bracketing intervals.
