### ISSUE TITLE
Does ForwardDiff need to be a dependency?

### ISSUE THREAD

**Issue by rafaqz** [JuliaMath/Roots.jl#112]
Requires.jl could be used to remove this... I'm not sure its for commonly used functions anyway

**Comment by jverzani** [comment]
Is there an issue with the dependency? It is heavy for the amount of use it gets here, so could possibly be removed in favor of some documentation.

**Comment by rafaqz** [comment]
It pulls in quite a few packages and slows load time and CI. when Roots.jl is otherwise very lean!

I was watching my travis build and realised how much of the stack was pulled in by that one dependency. Forward diff requires:

Compat 0.47.0
StaticArrays 0.5.0
DiffResults 0.0.1
DiffRules 0.0.4
NaNMath 0.2.2
SpecialFunctions 0.1.0
CommonSubexpressions 0.1.0

That half of the deps for one of my packages, and I don't use the functionality at all.

If you use a `@require` block you can keep Newton etc with ForwardDiff deps, they will just be exposed when ForwardDiff is actually loaded.

**Comment by rafaqz** [comment]
I'll put together a pull request if that helps

**Comment by jverzani** [comment]
I’d say better to remove and document how forwarddiff can be used. I can do
that. If no one says whoa, give me a week.

**Comment by rafaqz** [comment]
Ok if that's a better option. Another option is Roots that need a jacobian (or whatever it is) could be in another package.

**Comment by KristofferC** [comment]
Please not another package.

**Comment by ararslan** [comment]
Also please don't introduce a dependency on Requires.

**Comment by rafaqz** [comment]
Just out of curiosity what wrong with a dep on Requires? I've started using requires remove other deps, thinking that was an ok option?

**Comment by ararslan** [comment]
It's a hack that's not really sound when it comes to precompilation. Better to wait until the language has first-class support for optional dependencies.

**Comment by rafaqz** [comment]
Thanks that is good to know. Optional deps will solve a lot of problems.

**Comment by rafaqz** [comment]
Requires seems to be a reliable solution for this kind of thing now: https://github.com/MikeInnes/Requires.jl/pull/46

**Comment by jverzani** [comment]
That's good to know. I still think it best to remove ForwardDiff and document (though I really want this for my private pedagogical issues, but it does seem too heavy to pull in during testing). This is next on my todo list for this package.
