### ISSUE TITLE
Test failure in OrdinaryDiffEq.jl

### ISSUE THREAD

**Issue by YingboMa** [JuliaMath/Roots.jl#129]
Upgrading Roots.jl to `v0.7.0` caused the following tests failures.
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/ode/ode_event_tests.jl#L160
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/85420e5f7f092bcba7e2e9ce167958a2529370c7/test/ode/ode_add_steps_tests.jl#L55

**Comment by jverzani** [comment]
Can you point out where the roots call is? I’m not familiar with the code base.

**Comment by jverzani** [comment]
Thanks, I think @ChrisRackauckas notified me of this. I removed support for a certain naming of tolerances. I can add them back if desired, but I got the sense this wasn't being requested.

**Comment by ChrisRackauckas** [comment]
The issue isn't the naming. We changed the naming. The issue is that things are not converging properly with the new version of roots. We haven't traced down exactly what's going on yet though.

**Comment by jverzani** [comment]
Maybe try Roots.AlefeldPotraShi? The FalsePosition methods don't always
converge. Something I need to investigate. The latter is as fast and uses
fewer function calls in the test suite in RootTesting

```

julia> run_tests((f,b) -> Roots.find_zero(f,  b, Roots.AlefeldPotraShi()),
name="APS")

MethodResults(APS, evalcount=2266, numfailures=0,
maxresidual=3.552713678800501e-15)


julia> run_tests((f,b) -> Roots.find_zero(f,  b, Roots.FalsePosition()),
name="APS")

MethodResults(APS, evalcount=2869, numfailures=8,
maxresidual=7.957476190023453e-12)
```

**Comment by ChrisRackauckas** [comment]
Good this worked.
