### ISSUE TITLE
Add CHANGELOG/NEWS file

### ISSUE THREAD

**Issue by Datseris** [JuliaMath/Roots.jl#131]
A lot of people depend here. DynamicalSystems.jl included. After latest update I have the same problems as in #129 ...

Please add some kind of NEWS.md or CHANGELOG.md file when making breaking changes.

**Comment by jverzani** [comment]
Fair enough. I moved a lot of pieces around. Is yours the same problem or a different one? I have a fix for that one I am just testing now. though the recommendation to avoid FalsePosition in favor of AlefeldPotraShi is still the better one.

**Comment by Datseris** [comment]
I fixed my problem by using A42() instead of FalsePosition. But I also raised the tolerances to 1e-6 from 1e-3 to get same "accuracy".

**Comment by jverzani** [comment]
Ahh. I', guessing that was a bug fix on how f(x) ~ 0 was being determined that made the difference. If you have a simple example to copy over, I'd be curious to look at it.

**Comment by Datseris** [comment]
> If you have a simple example to copy over, I'd be curious to look at it.

Nope sorry, it is a really complicated case where the function to find the root of is actually a multidimensional interpolation from DiffEq. If you want you can look here: 

https://github.com/JuliaDynamics/ChaosTools.jl/blob/master/src/orbitdiagrams/poincare.jl#L64

https://github.com/JuliaDynamics/ChaosTools.jl/blob/master/src/orbitdiagrams/poincare.jl#L97-L104

https://github.com/JuliaDynamics/ChaosTools.jl/blob/master/src/orbitdiagrams/poincare.jl#L126-L130

but I really wouldn't recommend :D

**Comment by jverzani** [comment]
Yeah, that's complicated! Even with the increased tolerance, on the test
suite there are about 2/3rds as many function calls taken by A42, than by
FalsePosition, so it should be a bit faster now.
