### ISSUE TITLE
Root of function with multiple inputs

### ISSUE THREAD

**Issue by EoinMcEvoy** [JuliaMath/Roots.jl#136]
In Matlab, using fzero it is possible to indicate which variable to alter in a multivariable function when searching the root. For example, with fixed values for y and z, I want to find the value for x that zeros the function:

```matlab
y=1;
z=1;
val = fzero(@(x) someFunction(x,y,z),1);
```
or instead now the value for y:

```matlab
x=1;
z=1;
val = fzero(@(y) someFunction(x,y,z),1);
```
etc.

I am new to Julia and maybe just cannot find the correct syntax, but is this possible with the Roots package?

**Comment by KristofferC** [comment]
This is called creating a closure:

```
julia> const x = 2
2

julia> const y = 3
3

julia> f(x,y) = exp(x+3y) - (x+3y)^4

julia> x_sol = find_zero(x -> f(x,y), (-20,20))
-0.3868305435586014

julia> f(x_sol, y)
1.8189894035458565e-12

julia> y_sol = find_zero(y -> f(x,y), (-20,20))
2.2043898188138

julia> f(x, y_sol)
1.8189894035458565e-12
```
