### ISSUE TITLE
Support finding roots with Dual Numbers.

### ISSUE THREAD

**Issue by lstagner** [JuliaMath/Roots.jl#146]
I am attempting to find the Jacobian of a transformation that involves root-finding. When I try to use ForwardDiff to calculate the Jacobian I get the following error. 

```
MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##6#7")),Float64},Float64,4})
Closest candidates are:
  Float64(::Real, !Matched::RoundingMode) where T<:AbstractFloat at rounding.jl:185
  Float64(::T<:Number) where T<:Number at boot.jl:725
  Float64(!Matched::Int8) at float.jl:60
  ...

Stacktrace:
 [1] convert(::Type{Float64}, ::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##6#7")),Float64},Float64,4}) at ./number.jl:7
 [2] update_state(::Roots.AlefeldPotraShi, ::Roots.DerivativeFree, ::Roots.UnivariateZeroState{Float64,ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##6#7")),Float64},Float64,4}}, ::Roots.UnivariateZeroOptions{Float64,Float64,Float64,ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##6#7")),Float64},Float64,4}}) at /home/lstagner/.julia/packages/Roots/hYq0I/src/bracketing.jl:644
```

This issue arose out of https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/169#issuecomment-431603474

**Comment by lstagner** [comment]
I've tracked down the error to this [line](https://github.com/JuliaMath/Roots.jl/blob/905560797df126ff2c5aa770c8925abcbb3b2326/src/bracketing.jl#L645)

    c::T = newton_quadratic(a, b, d, fa, fb, fd, 2, delta)

The problem is that the type assertion,`c::T` is trying to convert the DualNumber into a Float64.

**Comment by ChrisRackauckas** [comment]
The fix would be to use `ForwardDiff.value` of the result. Using the equivalent for Unitful, etc. would be required to make the other number types work. To make the full set of standard number types work, you can basically look at:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/init.jl#L6-L44

and do something similar. Julia is currently missing a generic `value` function which makes this more difficult than it should be.

**Comment by lstagner** [comment]
@ChrisRackauckas I tried what you suggested and while I can get it to run without throwing an error it gives the wrong answer (as compared to finite differencing). The issue was partially my fault as I needed to have the independent variable be a Dual number since that is what I am trying to find a derivative of. When I did that I ran into the problem of `nextfloat`/`prevfloat` not being defined for Dual (which also needed to be defined for DiffEqBase).

That was fixed by defining
```
Base.nextfloat(d::Dual{N,T}) where {N,T} = Dual(nextfloat(d.value), nextfloat.(d.partials)...) 
Base.prevfloat(d::Dual{N,T}) where {N,T} = Dual(prevfloat(d.value), prevfloat.(d.partials)...)
```
But then I run into other issues/warnings about the ForwardDiff tags. After turning off tag checking I get it to run although it gives me a different answer than finite differencing. So ... ¯\_(ツ)_/¯. Anyway other than the `prevfloat`/`nextfloat`, which is a ForwardDiff issue, I don't think there is an issue with Roots so I'm closing this for now.

**Comment by lstagner** [comment]
Correction the `prevfloat`/`nextfloat` definitions need to be
```
Base.nextfloat(d::Dual{T,V,N}) where {T,V,N} = Dual{T}(nextfloat(d.value), nextfloat.(d.partials)...) 
Base.prevfloat(d::Dual{T,V,N}) where {T,V,N} = Dual{T}(prevfloat(d.value), prevfloat.(d.partials)...)
```
in order to preserve the tag information.

**Comment by ChrisRackauckas** [comment]
Yeah. That's interesting, since our test case that worked before still works:

```julia
using DiffEqSensitivity, ParameterizedFunctions
using OrdinaryDiffEq, Calculus

f = @ode_def AAA begin
    dx = -a
    dy = b
end a b

cb = ContinuousCallback((u,t,i) -> u[1], (integrator)->(println("Stopped.");integrator.p[2]=0.0))
p = [2.0, 1.0]

function test_f(p)
  prob = ODEProblem(f,eltype(p).([1.0,0.0]),eltype(p).((0.0,1.0)),copy(p))
  solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14,callback=cb,save_everystep=false)[end]
end
p = [2.0, 1.0]
findiff = Calculus.finite_difference_jacobian(test_f,p)
findiff

Base.nextfloat(d::ForwardDiff.Dual{T,V,N}) where {T,V,N} = ForwardDiff.Dual{T}(nextfloat(d.value), nextfloat.(d.partials)...) 
Base.prevfloat(d::ForwardDiff.Dual{T,V,N}) where {T,V,N} = ForwardDiff.Dual{T}(prevfloat(d.value), prevfloat.(d.partials)...)
using ForwardDiff
ad = ForwardDiff.jacobian(test_f,p)
ad
```
