### ISSUE TITLE
Broadcasting supported?

### ISSUE THREAD

**Issue by giannamars** [JuliaMath/Roots.jl#166]
Is broadcasting supported for Roots.find_zero()?

E.g.

`f(x) = [sin(x), cos(x)];
out = Roots.find_zero.(f, zeros(2))`

only returns the solution for sin(x): out = [0, 0].

Thanks,
Gianna

**Comment by jverzani** [comment]
You would need to pass two function objects, not a two dimensional function, as with:

```
f = [sin, cos]  # or [x->sin(x), x->cos(x)]
find_zero.(f, zeros(2))
```
