### ISSUE TITLE
Optionally return the smallest interval

### ISSUE THREAD

**Issue by MartinOtter** [JuliaMath/Roots.jl#170]
In DifferentialEquations.jl an [issue](https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/551) is reported that could probably be solved with a missing option in Roots.jl:

DifferentialEquations.jl uses Roots.jl for event detection: The zero crossing of f(t) defines an event (where t is time). With a bracketing method an interval is computed [t1,t2] in which the root resides. For event handling of differential equations it is important that the root is returned that has an opposite sign as the zero crossing function had before the event. This means that as root t2 should be used, since it is guaranteed that `f(t2)*f(t1)<=0`. Roots.jl seems to return a more precise approximation of the root `t1 <= tstar <= t2`, but there is no guarantee that `f(tstar)*f(t1) <= 0`.

It would be very helpful for DifferentialEquations.jl if an option could be added to Roots.jl so that optionally the interval of the result point is also returned, something like:
```
tstar, (t1,t2) = find_zero(...; returnInterval=true) 
```
(info to @ChrisRackauckas)

**Comment by jverzani** [comment]
This is possible, but would require some reworking of the convergence assessment functions to make it happen. At one point, the default for bracketing was bisection, but this was switched to the A42 method, as it typically takes far fewer steps. Do you know which method is called?

There is an issue to consider, as to what to do when an exact 0 is found and not a zero crossing.

**Comment by ChrisRackauckas** [comment]
@kanav99

**Comment by kanav99** [comment]
`AlefeldPotraShi` is used in DifferentialEquations.

**Comment by jverzani** [comment]
Does #173 provide a reasonable interface for this purpose? It introduces an alternative function  `Roots.find_bracket` to provide  the bracket (instead of a keyword argument).

**Comment by MartinOtter** [comment]
Y

> 
> 
> Does #173 provide a reasonable interface for this purpose? It introduces an alternative function `Roots.find_bracket` to provide the bracket (instead of a keyword argument).

Thanks very much. Yes, this looks good.
