### ISSUE TITLE
Strange results when solving a differential equations with callbacks involving Measurements.jl

### ISSUE THREAD

**Issue by giordano** [JuliaMath/Roots.jl#171]
*I'm moving here the discussion about an issue initially reported to https://github.com/JuliaPhysics/Measurements.jl/issues/64/.  CC: @MartinOtter*

---

Consider the following differential equation:
```julia
using DifferentialEquations, Measurements

function f(du,u,p,t)
    du[1] = u[2]
    du[2] = -9.81
end

function condition(u,t,integrator)
    return u[1] + 1e-12
end

const restitution = 0.7 ± 0.1   # coefficient of restitution

function affect_neg(integrator)
    println("Event at time = ", integrator.t, ", h = ", integrator.u[1])
    v_before = integrator.u[2]
    @show v_before
    @show Measurements.derivative(v_before, restitution)
    v_after = -restitution*v_before
    @show v_after
    @show Measurements.derivative(v_after, restitution)

    integrator.u[2] = v_after
    auto_dt_reset!(integrator)
    set_proposed_dt!(integrator, integrator.dt)
    println()
end

cb = ContinuousCallback(condition,nothing,affect_neg! = affect_neg)
u0 = [1.0 ± 0.2, 0.0]
tspan = (0.0 ± 0.0, 2.0 ± 0.0)
prob = ODEProblem(f,u0,tspan)
solve(prob,Tsit5(),saveat=0.01,callback=cb)
```

This gives the following output:
```
Event at time = 0.45152364098595665 ± 0.0, h = -0.0 ± 0.2
v_before = -4.42944691807223 ± 0.0
Measurements.derivative(v_before, restitution) = 0.0
v_after = 3.1 ± 0.44
Measurements.derivative(v_after, restitution) = 4.42944691807223

Event at time = 1.0836567383662938 ± 0.0, h = -0.0 ± 0.34
v_before = -3.1 ± 0.44
Measurements.derivative(v_before, restitution) = 4.42944691807223
v_after = 2.17042898985538 ± 1.8e-15
Measurements.derivative(v_after, restitution) = -1.7763568394002505e-14

Event at time = 1.5261499065325295 ± 0.0, h = -0.0 ± 0.34
v_before = -2.170428989855389 ± 1.8e-15
Measurements.derivative(v_before, restitution) = -1.7763568394002505e-14
v_after = 1.52 ± 0.22
Measurements.derivative(v_after, restitution) = 2.1704289898554014

Event at time = 1.8358951242488952 ± 0.0, h = -0.0 ± 0.4
v_before = -1.52 ± 0.22
Measurements.derivative(v_before, restitution) = 2.1704289898554014
v_after = 1.0635102050291443 ± 3.3e-16
Measurements.derivative(v_after, restitution) = -3.3306690738754696e-15
```

As discussed in https://github.com/JuliaPhysics/Measurements.jl/issues/64#issuecomment-581158057, I think that the problem is that the derivative of `v_before` with respect to `e` has the wrong sign: `v_before` has the opposite value of `v_after` in the preceding callback, but the sign of the derivative is the same.  Everything seems to work if we manually flip the sign of the derivative of `v_before`.

I'm reporting this issue here because I suspect there is a bad interaction between `Measurements.jl` and `Roots.jl`, which is called by `DiffEqBase.jl` in the callback.  If in the definition of `zero_func` at https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/2386f211a2228bb302a0145c039ffa9ca2d2b450/src/callbacks.jl#L539-L542 I add a `@show Θ` I see the following output:
```
Θ = 0.0 ± 0.0
Θ = 1.0 ± 0.0
Θ = 0.5 ± 0.0
Θ = 0.513 ± 0.085
Θ = 0.509 ± 0.088
Θ = 0.509 ± 0.088
Θ = 0.509 ± 0.088
Θ = 0.509 ± 0.088
Θ = 0.509 ± 0.088
Θ = 0.509 ± 0.088
Θ = 0.5089510673864017
Θ = 0.508951067386402
```
I verified these lines come from the `find_zero` at https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/2386f211a2228bb302a0145c039ffa9ca2d2b450/src/callbacks.jl#L561.

The fact that `Θ` is changing type is suspicious, but it might be also a red herring.  Do you have any clue of how to investigate this?  Unfortunately I can't provide a smaller working example, I'm a bit lost in the code of all these packages :slightly_smiling_face:

**Comment by MartinOtter** [comment]
Sorry, the issue is not find_root but the usage of find_root in DifferentialEquations.jl. Please, close this issue here (I am opening an issue at DifferentialEquations.jl)

**Comment by giordano** [comment]
I don't know where the exactly the problem lies, but [this method](https://github.com/JuliaMath/Roots.jl/blob/744533e1a1ac87fe17a5dc0488a87a7cc4ca8d5c/src/find_zero.jl#L526-L554) is definitely called, as far as I can see.

**Comment by giordano** [comment]
Ok, it turns out to be an issue in `Measurements.jl`.  Sorry for the noise!
