### ISSUE TITLE
verbose option missing from fzero()

### ISSUE THREAD

**Issue by simonp0420** [JuliaMath/Roots.jl#18]
Not sure if this is intended behavior:

``` Julia
julia> fzero(x -> x, [-1., 1.], verbose=true)
ERROR: no method find_zero(Function, Float64, Float64)
 in fzero at c:\home\simonp\.julia\v0.3\Roots\src\Roots.jl:63
```

It would be nice to have this option for all functions in Roots.

Thanks,
--Peter

**Comment by adityam** [comment]
One possibility could be to build this functionality on top of [Logging.jl](https://github.com/kmsquire/Logging.jl). It uses macros to reduce the overhead of conditional checking; but I have never explicitly measure the overhead.

**Comment by ikirill** [comment]
Root-finding iterations don't have that much useful information in them. I think the most common case is to want to know at which arguments the function gets evaluated, but that doesn't require fzero to do anything: you can just make a wrapper around the function that prints the arguments, and then pass the wrapper to fzero.
