### ISSUE TITLE
multi-variate root finding?

### ISSUE THREAD

**Issue by evanthebouncy** [JuliaMath/Roots.jl#20]
have we had any leads on how to do it for a multivariate setting?

**Comment by charleskawczynski** [comment]
Should this be closed since, it seems like, multivariate problems fall under the NLsolve domain?

**Comment by KronosTheLate** [comment]
Or NonlinearSolve.jl domain. But yes, this is not an issue with Roots.jl. The scope is specified in the first line of the readme:
"This package contains simple routines for finding roots of continuous scalar functions of a single real variable."

**Comment by longemen3000** [comment]
this should be closed then?

**Comment by KronosTheLate** [comment]
I think so
