### ISSUE TITLE
Gentler exit when no root exists

### ISSUE THREAD

**Issue by ghyatzo** [JuliaMath/Roots.jl#209]
Hello,

I was wondering if there was a way other than
```
try
    find_zero(f, (a,b))
catch
    missing
end
```

to handle the case when there is no root.

To contextualise: I am trying to find the solutions to a parametric integral function. And for a certain range of the parameter the solution does not exists (can be proven theoretically).
Exactly pinning down the critical value of the parameter from which to start looking at the solutions (knowing that they exist) is not always possible. Hence i found myself trying to find zeros in the whole range.

At first i used `find_zeros` which in case it doesn't find any root it simply returns an empty array which then can be handled via a simple `isempty()`. But when using `find_zero` for a parameter value without root, it crashes the whole computation instead of simply returning a return code.

I realise that the convergence error message can be helpful and also needed in other situations.
But maybe it can be changed to return a `missing` and print the convergence error as a warning so it doesn't distrupt other routines that implement the function and does not requires the use of `try ... catch ... end`.

**Comment by jverzani** [comment]
The syntax `find_zero(f, (a,b))` is *usually* guaranteed to return a root **if** [a,b] is a *bracketing* interval, and will error if not. So you should simply check if `sign(f(a)) * sign(f(b)) < 0`. If this isn't the case, then you might or might not have a zero (or more than one) in [a,b]. Starting with a single initial value, there is a way to get `find_zero` to return NaN when no zero is found, but the default is to error (which you are trying to avoid).

Now "usually" requires some detail: Over Float64, it will only find crossing points, so there is no guarantee the solution will correspond to a zero unless some continuity is assumed. Over different number types (think higher precision), a different algorithm is used and it doesn't always converge, as it assumes some differentiability.

**Comment by ghyatzo** [comment]
The function i was exploring the roots of was pretty heavy, and wanted to keep the evaluations to a minimum. So in my case it was just faster to let it error out and catch the error. 

Thanks for the explanation nonetheless!

**Comment by jverzani** [comment]
It isn't documented, but there is a means to reuse that initial computation for checking  by passing it in. See line https://github.com/JuliaMath/Roots.jl/blob/master/src/bracketing.jl#L91 for the function you use to initialize a "state". Additionally,  if you have a computationally heavy function, you might want to avoid the default Bisection method, which typically takes about 53 function calls over Float64 values. I'd suggest trying `Roots.A42()` for the bracketing method.

**Comment by ghyatzo** [comment]
This is really interesting, it could be very handy to write some words about it. If i understood correctly `fs` is the function reference and `xs` are the interval endpoints and `fxs` are the previously evaluated result for checking if we have a bracket.
I noticed that there are some inner methods that get a state as argument, but i am not really sure what is the right one to be called afterwards. Maybe a `function find_zero(fs, x0, method::AbstractUnivariateZeroMethod, state::AbstractUnivariateZeroState; tracks::AbstractTracks=NullTracks(), verbose=false, kwargs...)` could a nice addition to make everything a bit less obscure!

Unfortunately i could not really wrap my head around the `tracks` and the `verbose` part, which i saw later that it is relative to the logging. So i don't want to propose anything that might break things.

**Comment by jverzani** [comment]
Yes, it isn't obvious how this is done, but this is the pattern of calling `find_zero` with precomputed values and the default tolerances:

```
M = Roots.BisectionExact()
f(x) = sin(x)
xs = (3.0, 4.0)
fxs = f.(xs) 
state = Roots._init_state(M, f, xs, fxs)
find_zero(M, f, state)
```

The `_init_state` call will error is the signs of `fxs` aren't different with this `M`, but if you were doing what you did again, you could check that before calling.

**Comment by ghyatzo** [comment]
Awesome! It would be useful for future users to have these informations documented some where in the docs. I can add it myself if you prefer.
