### ISSUE TITLE
provide initial guess for bracketing methods

### ISSUE THREAD

**Issue by jherekhealy** [JuliaMath/Roots.jl#218]
the function 

init_state!(state::UnivariateZeroState{T,S}, ::AbstractAlefeldPotraShi, f, xs::Union{Tuple, Vector}, compute_fx=true) where {T, S}

uses internally c = _middle(a,b) as initial guess. Sometimes, we know a much better initial guess. IT would be great to be able to pass it, either via an argument, or by overriding some specific function.

**Comment by jverzani** [comment]
That seems reasonable. Do you want to put in a PR? If not, I'll have a look sometime soonish.

**Comment by jverzani** [comment]
HI @jherekhealy can you check if the linked PR is what you had in mind? Thanks.

**Comment by jherekhealy** [comment]
Thanks @jverzani 
This helps a little. Ideally, I would like to pass "middle" from the find_zero function. How would you do it with only init_state!(...) ?
The find_zero function call init_state(), which calls init_state!(..).

**Comment by jverzani** [comment]
It is pretty cumbersome, but it would look like this:

```
f(x) = x^5 - x - 1
x0 = (1,2)
M = Roots.AlefeldPotraShi()
state = Roots.init_state(M, f, x0)  # initial state
Roots.init_state!(state, M, f, (state.xn1, state.xn0), false, 1.5)  # would use 1.5 for middle, not _middle.
```

The middle value is used in `init_state!` and not stored as is, so there isn't a real short cut that I see at first glance.

**Comment by jverzani** [comment]
(That is with the most recently tagged version)

**Comment by jherekhealy** [comment]
Thanks! I thought it would be more cumbersome than this. This is good enough for me.
