### ISSUE TITLE
muller inefficient

### ISSUE THREAD

**Issue by jacobwilliams** [JuliaMath/Roots.jl#221]
The `muller` function is very inefficient since it's recomputing all three function evaluations every iteration, even though two of them have already been computed in the previous iteration.

**Comment by jacobwilliams** [comment]
Just sent a PR for this. I haven't looked at any of the other methods to see if they have the same problem.

**Comment by jverzani** [comment]
Thanks for this! I'll merge in and bump the version number once the tests run.
