### ISSUE TITLE
Bisection methods try values outside of the bounds

### ISSUE THREAD

**Issue by davidanthoff** [JuliaMath/Roots.jl#233]
Using the simple bisection algorithm, if a root is exactly on one of the bounds, then https://github.com/JuliaMath/Roots.jl/blob/65a503ae44548b7eeac3be8cc9da921b7565881d/src/find_zero.jl#L435 ends up evaluating `F` at a point that is outside of the user specified bounds. That is a problem, because it means one can't use this with functions that crash or are not defined outside of the bounds that the user specifies. That seems unnecessary, i.e. ideally the bisection method would guarantee to never eval the user function with values that are outside of the user specified bounds.

**Comment by jverzani** [comment]
Yes, definitely unintended.  That trade off to check for an exact crossing seems to complicated now.   Thanks for pointing this out.   I’m in the middle of a restructuring and this is informative.

**Comment by jverzani** [comment]
This was closed in #234. Thanks again.
