### ISSUE TITLE
`fzero` does not error out when a function has an asymptote and returns a value that is not a root

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaMath/Roots.jl#269]
the function `f(ω) = 3 + 1/ω` does not have a positive root, yet the `fzero` function below returns a root of `4e16` instead of failing.
shouldn't the expected behavior be an error that it failed to find a root? my code goes along running, assuming it found a root (dangerous).

```julia
r = fzero(ω -> 3 + 1/ω, 0.1, atol=2*sqrt(eps()))
```

I suspect this is b/c the gradient flow takes you along the asymptote to `ω=4e16` and then the `ω_{n+1}` does not differ much from `ω_n` and it returns a result (the second convergence criteria in the screenshot below). however, should there be a check before returning the root, to make sure `isapprox(r, 3 + 1/r, atol=atol)`?

![image](https://user-images.githubusercontent.com/30643894/147887906-fce06f7b-35c1-47b6-896a-406e51a32a73.png)

**Comment by jverzani** [comment]
The issue is there is `atol` *and* `rtol`, both non-zero by default. The `rtol` being non-zero allows run away answers like this one. Setting `rtol=0.0` will work here. (Where it won't work though is if you have an aggressive `atol` and a large root; one where `eps(x) > atol` or some such). There are some details buried in the docs (https://docs.juliahub.com/Roots/o0Xsi/1.3.13/roots/#Tolerances).

**Comment by SimonEnsemble** [comment]
thanks. indeed
```julia
r = fzero(ω -> 3 + 1/ω, 0.1, rtol=0.0)
```
properly throws a `Roots.ConvergenceFailed`. :+1:

awkward, but I see there is not a notion of relative error in `f(x_n)` since `f(x_n) / 0` is undefined, hence your definition of relative error using the magnitude of the root, via `| f(x_n) | <= rtol * abs(x_n)`. :laughing:

**Comment by SimonEnsemble** [comment]
P.S. if welcome, I could make a PR with this example in the documentation right after this.

![image](https://user-images.githubusercontent.com/30643894/147966944-044c7f12-1ec4-470c-9cb8-f125ee0470df.png)

As a consequence of this default definition of convergence, e.g. the function `f(x) = 3 + 1 / x`, which has no positive root, will return a very large (spurious) root without throwing a `ConvergenceFailed` error when provided an initial guess that is positive (owing to gradient flow).
```julia
r = fzero(x -> 3 + 1 / x, 0.1) #  r = 4.058155455175167e16
```
However, a `ConvergenceFailed` error is thrown when `rtol=0.0`:
```julia
r = fzero(x -> 3 + 1 / x, 0.1)  #  ERROR: Roots.ConvergenceFailed("Algorithm failed to converge")
```
