### ISSUE TITLE
Tracker works poorly for bracketing methods

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaMath/Roots.jl#277]
See the following output:
```
julia> for solver in (Roots.Secant(), Roots.Bisection(), Roots.FalsePosition(), Roots.ITP())
           tracker = Roots.Tracks()
           find_zero(f, (0, 2), solver, tracks=tracker, atol=1e-1)
           println()
           @show solver
           @show tracker.fs
           @show length(tracker.xs)
           @show length(tracker.fs)
       end

solver = Secant()
tracker.fs = [-2.0, 2.0, -1.0, -0.22222222222222232, 0.04081632653061229]
length(tracker.xs) = 5
length(tracker.fs) = 5

solver = Bisection()
tracker.fs = [-2.0, 2.0]
length(tracker.xs) = 28
length(tracker.fs) = 2

solver = FalsePosition{:anderson_bjork}()
tracker.fs = [-2.0, 2.0]
length(tracker.xs) = 8
length(tracker.fs) = 2

solver = Roots.ITP{Float64, Int64}(0.2, 2, 1)
tracker.fs = Float64[]
length(tracker.xs) = 12
length(tracker.fs) = 0
```

The number of, and value of, the `fs` field of the tracker are plain nonsense for the bracketing methods. I have no idea what goes wrong, but a fix should not be complicated, seeing as the algorithms compute good solutions.

**Comment by jverzani** [comment]
The bracketing methods track the bracketing interval, so the xs are read  in by pairs. The proper fix would be to have different tracks for the two different methods. If we went down that road, a rename would then be reasonable.

**Comment by KronosTheLate** [comment]
Yhea I do not think I am a fan of that. I like the current `xs` and `fs`, but would like `xs` to have element-type Tuple for bracketing methods.

If this is the case, I guess the `Traces` constructor could take a kwarg, resulting in `Traces(bracketing=true)` being equivalent to `Trackes(Tuple(Float64, Float64), Float64)`.

**Comment by jverzani** [comment]
My working PR has two fields `xfs` of type Vector{Tuple{T,S}} and `abs` of type Vector{Tuple{T,T}}. It is an improvement, especially for tracing the *default* method of `find_zero(f, a)`. I'll have that up for discussion in a bit.
