### ISSUE TITLE
Change format of `xs` field of Tracks

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaMath/Roots.jl#278]
The current way to print a trace to the terminal is excellent:

```
julia> using Roots

julia> f(x) = x^2-2
f (generic function with 1 method)

julia> tracker = Roots.Tracks()
Algorithm has not been run

julia> find_zero(f, (0, 2), Roots.Bisection(), tracks=tracker, atol=1e-1)
1.4375

julia> tracker
Results of univariate zero finding:

* Converged to: 1.4375
* Algorithm: Bisection()
* iterations: 13
* function evaluations ≈ 16
* stopped as |f(x_n)| ≤ max(δ, |x|⋅ϵ) using δ = atol, ϵ = rtol

Trace:
(a_0, b_0) = ( 0.0000000000000000,  2.0000000000000000)
(a_1, b_1) = ( 0.0000000000000000,  2.0000000000000000)
(a_2, b_2) = ( 0.0000000000000000,  2.0000000000000000)
(a_3, b_3) = ( 0.0000000000000000,  2.0000000000000000)
(a_4, b_4) = ( 0.0000000004656613,  2.0000000000000000)
(a_5, b_5) = ( 0.0000305175781250,  2.0000000000000000)
(a_6, b_6) = ( 0.0078125000000000,  2.0000000000000000)
(a_7, b_7) = ( 0.1250000000000000,  2.0000000000000000)
(a_8, b_8) = ( 0.5000000000000000,  2.0000000000000000)
(a_9, b_9) = ( 1.0000000000000000,  2.0000000000000000)
(a_10, b_10) = ( 1.0000000000000000,  1.5000000000000000)
(a_11, b_11) = ( 1.2500000000000000,  1.5000000000000000)
(a_12, b_12) = ( 1.3750000000000000,  1.5000000000000000)
(a_13, b_13) = ( 1.3750000000000000,  1.4375000000000000)

# I note that the interval is not actually halved at each iteration in the start, and will make a new issue for that
```

But when accessing the `xs` field, when a bracketing method is used, the values are simply stored one after another, where two successive values _together_ represent the interval:
```
julia> tracker.xs
28-element Vector{Float64}:
 1.4916681462400413e-154
 2.0
 1.727233711018889e-77
 2.0
 5.877471754111438e-39
 2.0
 1.0842021724855044e-19
 2.0
 4.656612873077393e-10
 2.0
 3.0517578125e-5
 2.0
 0.0078125
 ⋮
 0.5
 2.0
 1.0
 2.0
 1.0
 1.5
 1.25
 1.5
 1.375
 1.5
 1.375
 1.4375
```

I think that this is a mistake, in that it makes the output extremely hard to read, without any clear benefits. I would suggest one of the following:
1) Make `xs` a matrix, with a column for each interval-limit.
2) Make `xs` a vector of tuples, which clearly belong together. 

Both options are readable, and clear improvements IMO. It is also nice that the type of `xs` changes for bracketing problems, because the `xs` are fundamentally different for bracketing vs non-bracketing problems, and I like that that this is reflected in the type of `xs`.

**Comment by jverzani** [comment]
Having two different types would be fine, but does mean the calling function needs to have a means to call one or the other based on the method. (Not hard, just would be needed.)

Though, if this was really done properly, it might be best to have *two* fields for the xs! Why, the tracks object for the hybrid methods (Order0) doesn't record the bracketing part. On first glance, that would be a nice improvement.
