### ISSUE TITLE
Documentation with `gh-pages` branch?

### ISSUE THREAD

**Issue by hyrodium** [JuliaMath/Roots.jl#312]
This repository has `docs` directory, but the deployment is not enabled, and the documentation is not hosted on github pages.
The only hosted documentation is on JuliaHub. https://juliahub.com/docs/Roots/

https://github.com/JuliaMath/Roots.jl/blob/08e1c81a97437ec46808de1af9deb3387ec9fe9a/docs/make.jl#L15-L17

Is this intended? I think it would be better to have the deployment because it will be useful to be able to see the document before tagging.

**Comment by jverzani** [comment]
"Is this intended?" Yes, but for no good reason except the need to set this up. Thanks for helping here. Let's see if it all works out after I merge your PR and update the settings.

**Comment by jverzani** [comment]
Hi @ararslan -- I don't have permissions to adjust the settings for Roots so that the documentation points to the gh-pages branch. (So was just leveraging the juliahub link). @hyrodium is encouraging me to host the documentation in the standard way, and I need some assistance from a `JuliaMath` owner. Many thanks.

**Comment by hyrodium** [comment]
The `dev` documentation has been deployed here: https://juliamath.github.io/Roots.jl/dev/
But, the versioned documentation is not deployed yet: https://juliamath.github.io/Roots.jl/stable/

We can try building versioned documentation by pushing a git tag such as `v2.0.0+doc1`.
See [Documentaer.jl's documentation](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/) for more information.
(Perhaps, `DOCUMENTER_KEY` is already enabled.)

**Comment by ararslan** [comment]
> I don't have permissions to adjust the settings for Roots so that the documentation points to the gh-pages branch.

You should now have full administrator rights on this repository. Let me know if there's anything else you need.

**Comment by jverzani** [comment]
Many thanks!
