### ISSUE TITLE
Initial value and interval of search

### ISSUE THREAD

**Issue by mahaa2** [JuliaMath/Roots.jl#320]
Hi,

Is there a way in which I can pass an initial value and some interval of search ? 

Thanks.

**Comment by jverzani** [comment]
There is an internal way to pass the initial "middle" value to the AlefeldPotraShi methods along with the bracket. This was requested as values for (c,f(c)) had already been computed in some scenario and this saved a function evaluation. If that is what you want, let me know and I can try and find an example.

**Comment by mahaa2** [comment]
Hi, 

Yes. That looks like what I need.  Thanks.

**Comment by jverzani** [comment]
Closing. Please re-open if there is still a question.
