### ISSUE TITLE
slow parameters in solve interface?

### ISSUE THREAD

**Issue by longemen3000** [JuliaMath/Roots.jl#323]
Reproducer:
```
using Roots, BenchmarkTools
f(x,p = 1.0) = x^2 - p
prob = ZeroProblem(f,(0.0,10.0)
@btime solve(prob,Bisection()) # 970.000 ns (1 allocation: 16 bytes), that allocation is probable prob on global scope
@btime solve(prob,Bisection(),p) #1.470 μs (12 allocations: 304 bytes)
```
seems that passing `p` causes some type-instability? the tests in https://github.com/JuliaMath/Roots.jl/blob/master/test/test_allocations.jl doesn't seems to check passing parameters.
the line that handles this is here https://github.com/JuliaMath/Roots.jl/blob/48969e4f23f24bf418dbc06ec4e74df1ebfe8826/src/find_zero.jl#L281 , maybe change that conditional for `something(p,p′)` ?

**Comment by jverzani** [comment]
Thanks, that is unexpected. For comparison, we have 9 pesky allocations likely from a type instability, as you surmised:

```
julia> f(x,p = 1.0) = x^2 - p
f (generic function with 2 methods)

julia> using BenchmarkTools;@btime solve(Roots.ZeroProblem(f,(0.0,10.0)), Roots.Bisection(), p) setup=(p=1+rand())
  926.468 ns (9 allocations: 224 bytes)
1.0043810568912237

julia> g(x) = x^2 - 2.0
g (generic function with 1 method)

julia> @btime solve(Roots.ZeroProblem(f, (0.0, 10.0)), Roots.Bisection())
  759.263 ns (0 allocations: 0 bytes)
1.0
```

Let me look further to see how to address this.

**Comment by jverzani** [comment]
Thanks. Sorry I didn't read your comments more carefully at first. Surprisingly, to me, the issue seemed related to splatting of positional arguments and not that check.
