### ISSUE TITLE
How to force Roots.jl throw the last inaccurate result x even without converging?

### ISSUE THREAD

**Issue by zxm403089989** [JuliaMath/Roots.jl#341]
When using `fzero` or `Roots.find_zero` solving a equation, `Roots.assess_convergence` checks whether the algorithm converge or not. If not, one would receive `Roots.ConvergenceFailed("Algorithm failed to converge")`. However, sometimes I need an inaccurate result even it is not converged. For example, `FindRoots` in Mathematica, it always return an result although it is far away from correct answer, in some cases. I hope to use this feature in `Roots.jl` in some special problems. Is there any option can achieve this?

**Comment by jverzani** [comment]
You definitely have some options here. One thing that comes to mind is to handle the iteration manually, along the lines of the following:

```
P = ZeroProblem((tanh,x->sech(x)^2), 1)
itr = init(P, Roots.Secant())

x, state = iterate(itr)
while true
    @show x, state
    x_state = iterate(itr, state)
    isnothing(x_state) && break
    x, state = x_state
end

x
```

The value of x will have the last value, even if convergence isn't assessed. You could also dig into the state object in the conditional.

**Comment by zxm403089989** [comment]
Thanks for your response. Could we have similar results in `Roots.find_zero` or `fzero`? Not manual method.

**Comment by jverzani** [comment]
Yeah, that would be rather large breaking change. Right now, `find_zero` errors, using `solve` returns `NaN`, but the lower level iteration allows a fairly simple means to wrap that behaviour into a function.

```
function my_find_zero(f, x, M, args...; kwargs...)
P = ZeroProblem(f, x)
itr = init(P, M, args...; kwargs...)

x, state = iterate(itr)
while true
    x_state = iterate(itr, state)
    isnothing(x_state) && break
    x, state = x_state
end

x
end
```
