### ISSUE TITLE
weird results returnd by `find_zeors`

### ISSUE THREAD

**Issue by fangliu-tju** [JuliaMath/Roots.jl#369]
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 6 × AMD Ryzen 5 3500X 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)

(@v1.8) pkg> st Roots
Status `~/.julia/environments/v1.8/Project.toml`
  [f2b01f46] Roots v2.0.12

julia> g1(x) = sqrt(x^2-1)/x
g1 (generic function with 1 method)

julia> g2(x) = sqrt(abs(x^2-1))/x
g2 (generic function with 1 method)

julia> g3(x) = sqrt(x^2-1)/(x*sign(x^2-1))
g3 (generic function with 1 method)

julia> g4(x) = sqrt(abs(x^2-1))/(x*sign(x^2-1))
g4 (generic function with 1 method)

julia> xs = range(1.1,2,length=1000000)
1.1:9.000009000009e-7:2.0

julia> g1.(xs) == g2.(xs) == g3.(xs) == g4.(xs)
true

julia> find_zeros(g1,1.1,2),find_zeros(g2,1.1,2),find_zeros(g3,1.1,2),find_zeros(g4,1.1,2)
(Float64[], Float64[], Float64[], [1.6064589843050217, 1.688277135825698, 1.770095287344132, 1.8519134388648082, 1.9337315903832424])

julia> g4.(find_zeros(g4,1.1,2))
5-element Vector{Float64}:
 0.7826300569238687
 0.8057029460616074
 0.8251310711828377
 0.8416765379332529
 0.8559039342941868

I am not sure if it is a bug.

**Comment by longemen3000** [comment]
2.0.10 does not have the error, 2.0.12 has it

**Comment by longemen3000** [comment]
the problem is with `Roots.dfree`:
```
Roots.dfree(g4,1.6676136363635579) #generates a wrong root
1.6064589843050217
Roots.dfree(g1,1.6676136363635579) #fails
```

**Comment by jverzani** [comment]
Yes, definitely from #363. Thanks for the PR, let me have a look.

**Comment by jverzani** [comment]
This is something to be engineered around and #371 should do this. The issue comes from the asymptote at 0 which the algorithm happens to find as it searches for values that aren't bracketed.

**Comment by longemen3000** [comment]
nice!, feel free to close that PR if the cases work
