### ISSUE TITLE
Incorrect Results from A42() in v2.0.13

### ISSUE THREAD

**Issue by densmojd** [JuliaMath/Roots.jl#373]
Here's a MWE

```
f(x) = 1 - x / (x - 1)^2
xleft = 1 + eps(BigFloat) 
xright = 3 * xleft
x = find_zero(f, (xleft, xright))
```
where
f(xleft) $\approx$ -3.3E153
f(xright) $\approx$ 0.25

using v2.0.13
x $\approx$ 3.0
f(x) $\approx$ 0.25

using v2.0.12
x $\approx$ 2.6
f(x) $\approx$ 2.6E-77

The culprit seems to be in src/Bracketing/alefeld_potra_shi.jl. In newton_quadratic()

```diff
- (iszero(A) || isinf(A) || isnan(A)) && return a - fa / B
+ iszero(A) || isfinite(A)) && return a - fa / B
```
Changing the isfinite() to !isfinite() gave correct results.  Other similar lines of code are in calculateΔ(::A2425{K})
```diff
- if (isnan(fc) || isnan(c) || isinf(c))
+ if (isnan(fc) || isfinite(c))
```
and calculateΔ(::A57{K})
```diff
- if (isnan(fc) || isnan(c) || isinf(c))
+ if (!isfinite(fc) || isfinite(c))
```

**Comment by jverzani** [comment]
Arghh, that was sloppy of me. Thanks for finding and reporting so quickly. Will push a fix today and add your test.
