### ISSUE TITLE
`LithBoonkkampIJzermanBracket` does not accept functions of the form (f,f/f')

### ISSUE THREAD

**Issue by longemen3000** [JuliaMath/Roots.jl#377]
`LithBoonkkampIJzermanBracket` accepts only functions in the tuple form, instead of just one function  that returns ` (f,f/f')`
```
prob1a = Roots.ZeroProblem((sin,cos),(-0.1,0.1,0.001))
prob1b = Roots.ZeroProblem(x -> (sin(x), sin(x)/cos(x)),(-0.1,0.1,0.001))
Roots.solve(prob1a,Roots.LithBoonkkampIJzermanBracket()) #works
Roots.solve(prob1b,Roots.LithBoonkkampIJzermanBracket()) #fails
```
A consequence of this is that you cannot pass parameter `p` (does the tuple function accept `p`? i tried without sucess)

**Comment by jverzani** [comment]
Ahh, right. I'll have to fix this. Thanks for pointing it out. Hopefully I'll find time in the next week or so.

**Comment by jverzani** [comment]
This tagged now.  Thanks for the help!!

Now, what is it that Measurements.jl needs support with here?

**Comment by longemen3000** [comment]
Hahah, it is more of an, optimization: you could solve with `Measurements.value(p)`, and only do the last evaluation with the full `p` that contains the uncertainty

**Comment by jverzani** [comment]
Feel free to add an extension, if you want. As you pointed out, they are a great way to add features.

**Comment by jverzani** [comment]
Closing now. Thanks again!
