### ISSUE TITLE
Clarify version 1.9 mention in documentation `IntervalRootFinding` extension for `find_zeros` is regarding the Julia version number

### ISSUE THREAD

**Issue by JoelTrent** [JuliaMath/Roots.jl#388]
In the current documentation for `find_zeros` there's a note for the new package extension feature implemented in Julia 1.9, that will mean that `find_zeros` calls `IntervalRootFinding` when IntervalRootFinding is loaded and a Interval struct is provided. Would it be possible to explicitly state that this is for Julia version 1.9, instead of version 1.9? I thought this version number referred either to the version of Roots.jl or IntervalRootFinding.jl; I didn't know about the package extension feature in Julia 1.9 until now and I suspect there might be others that are the same!

See: https://juliamath.github.io/Roots.jl/stable/reference/#Roots.find_zeros

**Comment by jverzani** [comment]
Thanks. I added a small note in #389

**Comment by jverzani** [comment]
Closed with #389  Thanks again.

**Comment by JoelTrent** [comment]
Awesome, thank you
