### ISSUE TITLE
fzeros and roots issues with BigInt

### ISSUE THREAD

**Issue by Marandil** [JuliaMath/Roots.jl#40]
I'm trying to check existence of integer solutions for some polynomials defined over `BigInt`.
In cases the solutions does not exist (probably), both `fzeros` and `roots` crash. Here's MWE:
(> denotes output from julia interactive mode)

```
using Polynomials
using Roots

x = poly([BigInt(0)])
R = BigInt(2)^256
EQ = x^2 - R
> Poly(-115792089237316195423570985008687907853269984665640564039457584007913129639936 + x^2)
fzeros(EQ)
> 2-element Array{Number,1}:
  -340282366920938463463374607431768211456//1
  340282366920938463463374607431768211456//1

EQ = 12x^2 - R
> Poly(-115792089237316195423570985008687907853269984665640564039457584007913129639936 + 12x^2)
fzeros(EQ)
> ERROR: DimensionMismatch("dimensions must match")
 in - at ./arraymath.jl:96
 in agcd at /home/marandil/.julia/v0.4/Roots/src/Polys/agcd.jl:273

roots(EQ)
> ERROR: MethodError: `eigvals!` has no method matching eigvals!(::Array{BigFloat,2})
 in eigvals at ./linalg/eigen.jl:92
```

The same instructions, but for `x = poly([0])` and smaller R works just fine.

**Comment by jverzani** [comment]
Thanks for pointing this out. The `roots` call won't work until `eigvals` is defined for big matrices. The error with `fzeros` is something that I can look into, as that should work. I think there may be more optimized ways to do this type of task. (E.g., I'd try SymPy)
