### ISSUE TITLE
frule doesn't support closure/functor

### ISSUE THREAD

**Issue by oxinabox** [JuliaMath/Roots.jl#408]
when writing my code that wanted to use Roots.jl to find a root and also wanted to find the deriviative,
I had just written a closure that closed over all parameters,
and then I had fed the frule a tangent object for that closure.

and I couldn't understand why that tangent wasn't being passed on to the call to `frule_via_ad` until I looked at the code.

It should be easy enough to rewrite it to use explict parameters though.
but I had just assumed functors would be supported

**Comment by oxinabox** [comment]
The problem is if the function is a closure/functor and dervative information is provided for it,
then that information is just tossed away rather then being used.


For example:
```julia
using ChainRulesCore
using Diffractor: DiffractorRuleConfig
using Roots

struct Foo
    offset::Float64
end

(self::Foo)(x) = (x - self.offset)^2 - 4.0

foo = Foo(1.0)
dfoo = Tangent{Foo}(offset = -1.2)
zprob = ZeroProblem(foo, (0.0, 10.0))
dzprob = Tangent{typeof(zprob)}(F=dfoo)

frule(
    DiffractorRuleConfig(), 
    (NoTangent(), dzprob, NoTangent(), NoTangent(), NoTangent()),
    Roots.solve, zprob, Bisection(), nothing
)
# Outputs incorrect result: (3.0, ZeroTangent())
```

We can work around this, if `p` is not being used already, by using that:
```julia
call_param(x, p::Foo) = p(x)
zprob2 = ZeroProblem(call_param, (0.0, 10.0))

frule(
    DiffractorRuleConfig(), 
    (NoTangent(), NoTangent(), NoTangent(), dfoo),
    Roots.solve, zprob2, Bisection(), foo
)
# Outputs correct result: (3.0, -1.2)
```
A more complex work around that supposed both existing `p` and the need to put the function there would be somehting like `call_and_pass(x, (pf, pp)) = pf(x, pp)`, and then wrapping your functor `foo` and the parameter `p`  into a tuple `(foo, p)`

Closures/functors are a pretty natural way to talk about parameterized functions I find in julia.

**Comment by jverzani** [comment]
Thanks! Let me see what I can do here.

**Comment by jverzani** [comment]
Sorry this took *so* long to get to. I hope I addressed this issue satisfactorily, but I believe there is a bit of work do do here still.
