### ISSUE TITLE
Precompile fails on Windows for RootsForwardDiffExt (not on other package extensions)

### ISSUE THREAD

**Issue by braamvandyk** [JuliaMath/Roots.jl#409]
This may be a Julia error rather than Roots.jl, but since it is only on RootsForwardDiffExt..jl that I get the error, I thought to start here.

This is repeatable on my system, even after deleting the compiled files in ..\.julia\compiled\v1.9\RootsForwardDiffExt.

Roots.jl version 2.0.22

julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
  JULIA_NUM_THREADS = 8

The logged in user account is an admin account with full access to the folders. The folders have also been excluded from the antivirus's automatic scans - I thought that might be the cause.

When I check the folder, the 5SNbM_9R7rZ.dll file has not been created, only the 5SNbM_9R7rZ.ji file. There are however several other package extensions where both the *.ji and *.dll files are successfully created.

Any other ideas I could try to resolve this?

```
Precompiling project...
  ◐ Roots → RootsForwardDiffExt
  ◓ SparseDiffTools → SparseDiffToolsZygoteExt
  ◓ SciMLBase → SciMLBaseZygoteExt
  ◓ Optimization → OptimizationZygoteExt
┌ Error: Pkg.precompile error
│   exception =
│    IOError: stat("C:\\Users\\Braam\\.julia\\compiled\\v1.9\\RootsForwardDiffExt\\5SNbM_9R7rZ.dll"): permission denied (EACCES)
│    Stacktrace:
│      [1] uv_error
│        @ .\libuv.jl:100 [inlined]
│      [2] stat(path::String)
│        @ Base.Filesystem .\stat.jl:152
│      [3] isfile
│        @ .\stat.jl:461 [inlined]
│      [4] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
│        @ Base .\loading.jl:2265
│      [5] #249
│        @ C:\Users\Braam\.julia\juliaup\julia-1.9.3+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Pkg\src\API.jl:1438 [inlined]
│      [6] withenv(f::Pkg.API.var"#249#280"{IOBuffer, String, Base.PkgId}, keyvals::Pair{String, String})
│        @ Base .\env.jl:197
│      [7] (::Pkg.API.var"#248#279"{IOBuffer, String, Base.PkgId})()
│        @ Pkg.API C:\Users\Braam\.julia\juliaup\julia-1.9.3+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Pkg\src\API.jl:1436
│      [8] with_logstate(f::Function, logstate::Any)
│        @ Base.CoreLogging .\logging.jl:514
│      [9] with_logger
│        @ .\logging.jl:626 [inlined]
│     [10] macro expansion
│        @ .\timing.jl:393 [inlined]
│     [11] macro expansion
│        @ C:\Users\Braam\.julia\juliaup\julia-1.9.3+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Pkg\src\API.jl:1434 [inlined]
│     [12] (::Pkg.API.var"#245#276"{Bool, Bool, Pkg.Types.Context, Vector{Task}, Dict{Base.PkgId, String}, Dict{Base.PkgId, IOBuffer}, Pkg.API.var"#color_string#266", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Bool}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│        @ Pkg.API .\task.jl:514
└ @ Pkg.API C:\Users\Braam\.julia\juliaup\julia-1.9.3+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Pkg\src\API.jl:1302
```

**Comment by jverzani** [comment]
This is odd and, sadly, I'm not sure what to suggest. I don't think Roots is doing anything out of the usual here and the testing checks against a few types of installs. I can only guess it is some interaction. What if you try a temporary project directory and install both `Roots` and `ForwardDiff`, does that seem to work on its own?

**Comment by longemen3000** [comment]
seems weird, i cannot reproduce (windows, 1.9.3, Roots 2.0.22, ForwardDiff v0.10.36)

**Comment by braamvandyk** [comment]
I upgraded Julia to v1.9.4, recompiled the packages and the problem went away. I'm going to assume there was some glitch on my machine / Julia installation. Thanks for the help.
