### ISSUE TITLE
Roots.Chandrapatla() returns non-sential results when the interval is not bracketing

### ISSUE THREAD

**Issue by ArturDoshchyn** [JuliaMath/Roots.jl#441]
In my experience, using `find_zero()` with with bracketing methods always returns an error if the supplied interval is not in fact bracketing. Today, however, I discovered that `Roots.Chandrapatla()` does not do that, and instead silently fails and returns a non-sential result. I believe it would be good to make its behavior consistent with that of the other methods in order to avoid silent errors.

For example, if we define a function that does not have a root
`f(x) = 1 + x^2`
and apply `Roots.Chandrapatla()` to it on some interval
`find_zero(f, (10.0, 20.0), Roots.Chandrapatla())`
we get a non-sential result 2.149362113533461.

Apologies if I missed something in the discussion/documentation, and this behaviour is in fact intentional.

**Comment by jverzani** [comment]
Thank you!! I really appreciate this report and will address it soon.

**Comment by jverzani** [comment]
closed in #442; error thrown
