### ISSUE TITLE
Brent's method?

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaMath/Roots.jl#46]
Is there interest in adding a version of Brent's method? It seems that Roots.jl is using the technically superior ACM 748 algorithm, but Brent's is so common would it be of interest? I have ported over a version from the C code in scipy (both the brenth and brentq variants) which I could bring in line with the calling conventions of Roots.jl if it would be desired.

**Comment by jverzani** [comment]
It seems reasonable.

**Comment by KronosTheLate** [comment]
In line with this FR, I would like an implementation of Ridder's method, as my teacher swears to it, and I will most likely need it for my exam.
