### ISSUE TITLE
Re-enable AppVeyor

### ISSUE THREAD

**Issue by tkelman** [JuliaMath/Roots.jl#66]
It looks like it used to be running on @ChrisRackauckas' account, but hasn't triggered for 3 months https://ci.appveyor.com/project/ChrisRackauckas/roots-jl
Thought the repo moved to this organization earlier than that...

**Comment by ChrisRackauckas** [comment]
Yeah, I set it up after the repo moved to the org. I am not sure why it stopped. Nothing immediately jumps out to me in the appveyor.yml file.

**Comment by tkelman** [comment]
the webhooks have been returning error 400 `{"message":"PR and project repositories do not match."}`, maybe a bug in appveyor itself? cc @IlyaFinkelshteyn

**Comment by ChrisRackauckas** [comment]
I manually told it to build the commit and it's running now. So it seems like it's just not automatically triggering it right.

**Comment by IlyaFinkelshteyn** [comment]
Could you please check what is at `pull_request/base/repo/full_name` in failed pull request?

**Comment by tkelman** [comment]
Ah, that does still say `jverzani/Roots.jl` - so perhaps it was originally enabled too soon, and the redirects hadn't propagated all the way maybe?

**Comment by IlyaFinkelshteyn** [comment]
Let me please ask few more questions:
- Was PR made for https://github.com/jverzani/Roots.jl or https://github.com/JuliaMath/Roots.jl?
- Does both repos have AppVeyor webhook configured
  - If yes, which of them (or both) have the same webhook ID (last part in URL) which is configured in AppVeyor UI Setting https://ci.appveyor.com/project/ChrisRackauckas/roots-jl/settings?

**Comment by jverzani** [comment]
I think I need to address this. Hopefully what I did recently for SymPy will also work here. Checking now.

**Comment by ChrisRackauckas** [comment]
Do I need to do anything here? Are those settings visible or should I post them here?

**Comment by IlyaFinkelshteyn** [comment]
Settings are visible for people who have access to AppVeyor and GitHub account. I would not post webhook ID here: although we have number of preventive techniques against webhook ID abuse, I see no reason to expose it.

**Comment by tkelman** [comment]
looks like it's running again
