### ISSUE TITLE
guarded_secant_step sometimes returns NaN

### ISSUE THREAD

**Issue by ikirill** [JuliaMath/Roots.jl#88]
I have a rather complicated function (I can't exactly post it directly), and while using fzero on it, as `fzero(f, x0, xtol=tol)`, fzero sometimes passes NaN as the argument when calling my function, then fails with ConvergenceFailed. The exact call (https://github.com/JuliaMath/Roots.jl/blob/master/src/derivative_free.jl#L203) is

```
julia> Roots.guarded_secant_step(2.4834374384240188, 2.4834374384240188, -4.57887826543768e-8, -4.57887826543768e-8)
(NaN, true)
```
(i.e., alpha=beta and falpha=fbeta), and this causes fzero to fail with ConvergenceFailure.

It seems that update_state doesn't check the `issue` flag being returned.

Either it shouldn't return NaN in this corner case, or update_state should check the issue flag and not call the user function with NaN, but I'm not quite sure what behaviour is expected there.

*The iteration was actually converging well*, there was no convergence failure at all, and the difficulty with my function is just that it's not very numerically stable.

**Comment by jverzani** [comment]
I'll have a look. Seems like something we can guard against. For other checks, when an NaN value occurs, the current state is checked against a somewhat relaxed tolerance value for convergence.  

As an aside, After adding the `FalsePostion` methods, I was thinking this guarded step approach might be better removed. Have you tried the FalsePosition methods on this function? Might be worth doing. The example in the docs `?FalsePosition` is `find_zero(x -> x^5 - x - 1, [-2, 2], FalsePosition())`.
