### ISSUE TITLE
`a42` is implemented in a way that calls the function way too many times unnecessarily

### ISSUE THREAD

**Issue by ikirill** [JuliaMath/Roots.jl#93]
It seems that right now the Alefeld-Potra-Shi method is implemented in a way that doesn't save previous evaluations of the function, `a42` keeps calling the function at exactly the same value repeatedly. 

This is extremely inefficient: indeed the standard definition of order for a root finding method is *per function call*, which assumes that you don't call the function at the same place twice.

In particular, A42 is supposed to be a good root-finding method, but right now it does 8 times as much work (79) as the false position method (11), and is worse even than bisection, which takes "merely" 53. Notice how in https://github.com/JuliaMath/Roots.jl/blob/476921302b0fcfe7688f87ff9e2107669d562d48/src/bracketing.jl#L444, and the other functions that `a42` calls, all the values of `f` are evaluated anew. Because of this, it's simply not the same method, and it has a much lower order.

There are only nine (9!) different values here!

```
julia> nf=0; Roots.find_zero(x -> (global nf; nf += 1; @printf "[% 3d] %s\n" nf x; x*x-2.0), [0.0, 2.0], Roots.A42())
[  1] 0.0
[  2] 0.0
[  3] 0.0
[  4] 2.0
[  5] 0.0
[  6] 2.0
[  7] 0.0
[  8] 0.0
[  9] 2.0
[ 10] 1.0
[ 11] 1.0
[ 12] 2.0
[ 13] 1.0
[ 14] 2.0
[ 15] 0.0
[ 16] 1.0
[ 17] 2.0
[ 18] 1.4166666666666667
[ 19] 1.0
[ 20] 1.4166666666666667
[ 21] 1.0
[ 22] 1.4166666666666667
[ 23] 2.0
[ 24] 0.0
[ 25] 1.0
[ 26] 1.4166666666666667
[ 27] 2.0
[ 28] 0.0
[ 29] 1.0
[ 30] 1.4166666666666667
[ 31] 1.4149474760467686
[ 32] 1.0
[ 33] 1.4149474760467686
[ 34] 1.0
[ 35] 1.4149474760467686
[ 36] 1.4149474760467686
[ 37] 1.4149474760467686
[ 38] 1.0
[ 39] 1.0
[ 40] 1.4149474760467686
[ 41] 1.4132278858762035
[ 42] 1.4132278858762035
[ 43] 1.4149474760467686
[ 44] 1.4132278858762035
[ 45] 1.4149474760467686
[ 46] 1.0
[ 47] 1.4166666666666667
[ 48] 1.4132278858762035
[ 49] 1.4149474760467686
[ 50] 1.0
[ 51] 1.4166666666666667
[ 52] 1.4132278858762035
[ 53] 1.4149474760467686
[ 54] 1.414213562590307
[ 55] 1.4132278858762035
[ 56] 1.414213562590307
[ 57] 1.4132278858762035
[ 58] 1.414213562590307
[ 59] 1.4149474760467686
[ 60] 1.0
[ 61] 1.4132278858762035
[ 62] 1.414213562590307
[ 63] 1.4149474760467686
[ 64] 1.0
[ 65] 1.4132278858762035
[ 66] 1.414213562590307
[ 67] 1.4142135623730951
[ 68] 1.4132278858762035
[ 69] 1.4142135623730951
[ 70] 1.4132278858762035
[ 71] 1.4142135623730951
[ 72] 1.4142135623730951
[ 73] 1.4142135623730951
[ 74] 1.4132278858762035
[ 75] 1.4132278858762035
[ 76] 1.4142135623730951
[ 77] 1.4142135623730943
[ 78] 1.4142135623730943
[ 79] 1.4142135623730951
1.4142135623730951
```

This doesn't seem to happen for the false position method:
```
julia> nf=0; Roots.find_zero(x -> (global nf; nf += 1; @printf "[% 3d] %s\n" nf x; x*x-2.0), [0.0, 2.0], Roots.FalsePosition(2))
[  1] 0.0
[  2] 0.0
[  3] 2.0
[  4] 1.0
[  5] 1.3333333333333333
[  6] 1.4193548387096775
[  7] 1.4140625
[  8] 1.4142132882682559
[  9] 1.4142138198654344
[ 10] 1.41421356237307
[ 11] 1.414213562373095
1.414213562373095
```

**Comment by ikirill** [comment]
I fixed this in https://github.com/ikirill/Roots.jl/commit/f4504e00852d60095becfbae4a37094a2b5bd25e, but for easier testing I made a copy of a42 (it reduces the number for evaluations for RootTesting.jl from 22000 to 3300(?)), so I just need to copy the changes back to bracketing.jl.

**Comment by jverzani** [comment]
Just catching up here. Would you want to make a PR or would you want someone (me?) to integrate in  your changes? This definitely needs addressing.

**Comment by ikirill** [comment]
I'll make a PR.
