### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaMath/Roots.jl#96]
I see that tuples in `find_zero` hasn't been released yet. I was hoping there can be a tag so it can start being used in DiffEq for the false position methods. Thanks!

**Comment by jverzani** [comment]
Oh, sorry. Let me do that. I had wanted to merge in change for v0.6 syntax and drop v0.5 first, but that doesn't make much sense. Let me tag what is here then move forward.
